version: "3.9"
services:
  postgres1:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "VESNIN_205"
      POSTGRES_USER: "VESNIN_205"
      POSTGRES_PASSWORD: "VESNIN_205"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/train_station:/docker-entrypoint-initdb.d
      - ./docker/db/data/train_station:/var/lib/postgresql/data
      #- ./docker/db/config/train_station.conf:/var/lib/postgresql/data/pgdata/postgresql.conf
    ports:
      - "5432:5432"

  postgres2:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "VESNIN_205"
      POSTGRES_USER: "VESNIN_205"
      POSTGRES_PASSWORD: "VESNIN_205"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/library:/docker-entrypoint-initdb.d
      - ./docker/db/data/library:/var/lib/postgresql/data
      #- ./docker/db/config/library.conf:/var/lib/postgresql/data/pgdata/postgresql.conf
    ports:
      - "5433:5432"

  postgres3:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "VESNIN_205"
      POSTGRES_USER: "VESNIN_205"
      POSTGRES_PASSWORD: "VESNIN_205"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/hospital:/docker-entrypoint-initdb.d
      - ./docker/db/data/hospital:/var/lib/postgresql/data
      #- ./docker/db/config/hospital.conf:/var/lib/postgresql/data/pgdata/postgresql.conf
    ports:
      - "5434:5432"